// Autogenerated by Thrift Compiler (0.13.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
	"context"
	"flag"
	"fmt"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
	"github.com/apache/thrift/lib/go/thrift"
	"myGeneric"
)

var _ = myGeneric.GoUnusedProtection__

func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  TPersonResult getItemPerson(string bsKey, string rootID)")
  fmt.Fprintln(os.Stderr, "  TPeronSetResult getItemsPerson(string bsKey)")
  fmt.Fprintln(os.Stderr, "  TPeronSetResult getPersonsPagination(string bsKey, i32 offset, i32 limit)")
  fmt.Fprintln(os.Stderr, "  TPeronSetResult getPersonsOfTeam(string bsKey)")
  fmt.Fprintln(os.Stderr, "  TTeamResult getItemTeam(string bsKey, string rootID)")
  fmt.Fprintln(os.Stderr, "  TTeamSetResult getItemsTeam(string bsKey)")
  fmt.Fprintln(os.Stderr, "  TTeamSetResult getTeamsPagination(string bsKey, i32 offset, i32 limit)")
  fmt.Fprintln(os.Stderr, "  TTeamResult getPersonIsTeam(string bsKey)")
  fmt.Fprintln(os.Stderr, "  void putItemPerson(string bsKey, TPerson item)")
  fmt.Fprintln(os.Stderr, "  void putPersonIsTeam(string bsKey, string teamId)")
  fmt.Fprintln(os.Stderr, "  void putItemTeam(string bsKey, TTeam item)")
  fmt.Fprintln(os.Stderr, "  void putPersonToTeam(string bsKey, string personId)")
  fmt.Fprintln(os.Stderr, "  bool itemIsExist(string bsKey, string rootID)")
  fmt.Fprintln(os.Stderr, "  void removeItem(string bsKey, string rootID)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

type httpHeaders map[string]string

func (h httpHeaders) String() string {
  var m map[string]string = h
  return fmt.Sprintf("%s", m)
}

func (h httpHeaders) Set(value string) error {
  parts := strings.Split(value, ": ")
  if len(parts) != 2 {
    return fmt.Errorf("header should be of format 'Key: Value'")
  }
  h[parts[0]] = parts[1]
  return nil
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  headers := make(httpHeaders)
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Var(headers, "H", "Headers to set on the http(s) request (e.g. -H \"Key: Value\")")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http" || parsedUrl.Scheme == "https"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
    if len(headers) > 0 {
      httptrans := trans.(*thrift.THttpClient)
      for key, value := range headers {
        httptrans.SetHeader(key, value)
      }
    }
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := myGeneric.NewTGenericServiceClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "getItemPerson":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "GetItemPerson requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.GetItemPerson(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "getItemsPerson":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetItemsPerson requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetItemsPerson(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getPersonsPagination":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "GetPersonsPagination requires 3 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    tmp1, err36 := (strconv.Atoi(flag.Arg(2)))
    if err36 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    tmp2, err37 := (strconv.Atoi(flag.Arg(3)))
    if err37 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    fmt.Print(client.GetPersonsPagination(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "getPersonsOfTeam":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetPersonsOfTeam requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetPersonsOfTeam(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getItemTeam":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "GetItemTeam requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.GetItemTeam(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "getItemsTeam":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetItemsTeam requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetItemsTeam(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getTeamsPagination":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "GetTeamsPagination requires 3 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    tmp1, err43 := (strconv.Atoi(flag.Arg(2)))
    if err43 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    tmp2, err44 := (strconv.Atoi(flag.Arg(3)))
    if err44 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    fmt.Print(client.GetTeamsPagination(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "getPersonIsTeam":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetPersonIsTeam requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetPersonIsTeam(context.Background(), value0))
    fmt.Print("\n")
    break
  case "putItemPerson":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "PutItemPerson requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    arg47 := flag.Arg(2)
    mbTrans48 := thrift.NewTMemoryBufferLen(len(arg47))
    defer mbTrans48.Close()
    _, err49 := mbTrans48.WriteString(arg47)
    if err49 != nil {
      Usage()
      return
    }
    factory50 := thrift.NewTJSONProtocolFactory()
    jsProt51 := factory50.GetProtocol(mbTrans48)
    argvalue1 := myGeneric.NewTPerson()
    err52 := argvalue1.Read(jsProt51)
    if err52 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    fmt.Print(client.PutItemPerson(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "putPersonIsTeam":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "PutPersonIsTeam requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.PutPersonIsTeam(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "putItemTeam":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "PutItemTeam requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    arg56 := flag.Arg(2)
    mbTrans57 := thrift.NewTMemoryBufferLen(len(arg56))
    defer mbTrans57.Close()
    _, err58 := mbTrans57.WriteString(arg56)
    if err58 != nil {
      Usage()
      return
    }
    factory59 := thrift.NewTJSONProtocolFactory()
    jsProt60 := factory59.GetProtocol(mbTrans57)
    argvalue1 := myGeneric.NewTTeam()
    err61 := argvalue1.Read(jsProt60)
    if err61 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    fmt.Print(client.PutItemTeam(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "putPersonToTeam":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "PutPersonToTeam requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.PutPersonToTeam(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "itemIsExist":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "ItemIsExist requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.ItemIsExist(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "removeItem":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "RemoveItem requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.RemoveItem(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
